<?php
/** @var $arParams */
/** @var $arResult */
/** @var $APPLICATION */
if (!defined("B_PROLOG_INCLUDED") || B_PROLOG_INCLUDED !== true) die();

$APPLICATION->SetTitle($arResult['RAW_DISCOUNT']['NAME']);
$APPLICATION->AddChainItem($arResult['RAW_DISCOUNT']['NAME'], '/discounts/' . $arResult['RAW_DISCOUNT']['NAME'] . '/');
$curDateTime = new \Bitrix\Main\Type\DateTime();
?>

<div class="discount_detail">
    <div class="discount_detail_first">
        <?php if ($arResult['DISCOUNT_IBLOCK']['PICTURE']): ?>
            <?php $iblockImage = CFile::GetByID($arResult['DISCOUNT_IBLOCK']['PICTURE'])->fetch(); ?>
            <div class="discount_logo mt-5 mb-5">
                <img src="<?= $iblockImage['SRC'] ?>" class="detail_discount_image">
            </div>
        <?php endif; ?>
        <div class="discount_name mb-5">
            <h1><?= $arResult['RAW_DISCOUNT']['NAME'] ?></h1>
            <?php if (!empty($arResult['RAW_DISCOUNT']["ACTIVE_TO"])): ?>
                <h5 class="mb-4">Акция <?= ($arResult['RAW_DISCOUNT']["ACTIVE_FROM"] <= $curDateTime)
                        ? (($arResult['RAW_DISCOUNT']["ACTIVE_TO"] >= $curDateTime) ? 'проводится' : 'проводилась')
                        : 'будет проводиться' ?>
                    с <?= $arResult['RAW_DISCOUNT']["ACTIVE_FROM"]->format('d.m.Y') ?>
                    по <?= $arResult['RAW_DISCOUNT']["ACTIVE_TO"]->format('d.m.Y') ?></h5>
            <?php endif; ?>
            <span><?= $arResult['DISCOUNT_IBLOCK']['DESCRIPTION'] ?></span>
        </div>
    </div>
</div>
<div class="discount_products">
    <?php
    $test = 'test';
//    $sectionParams = array(
//        "IBLOCK_TYPE" => "1c_catalog",
//        "IBLOCK_ID" => IBLOCK_CATALOG,
//        "TEMPLATE_THEME" => "site",
//        "DETAIL_SHOW_MAX_QUANTITY" => "Y",
//        "HIDE_NOT_AVAILABLE" => "L",
//        "BASKET_URL" => "/personal/cart/",
//        "ACTION_VARIABLE" => "action",
//        "PRODUCT_ID_VARIABLE" => "ID",
//        "SECTION_ID_VARIABLE" => "SECTION_ID",
//        "PRODUCT_QUANTITY_VARIABLE" => "quantity",
//        "PRODUCT_PROPS_VARIABLE" => "prop",
//        "SEF_MODE" => "Y",
//        "SEF_FOLDER" => "/catalog/",
//        "AJAX_MODE" => "N",
//        "AJAX_OPTION_JUMP" => "N",
//        "AJAX_OPTION_STYLE" => "Y",
//        "AJAX_OPTION_HISTORY" => "N",
//        "CACHE_TYPE" => "N",
//        "CACHE_TIME" => "",
//        "CACHE_FILTER" => "Y",
//        "CACHE_GROUPS" => "Y",
//        "SET_TITLE" => "Y",
//        "ADD_SECTION_CHAIN" => "Y",
//        "ADD_ELEMENT_CHAIN" => "Y",
//        "SET_STATUS_404" => "Y",
//        "DETAIL_DISPLAY_NAME" => "N",
//        "USE_ELEMENT_COUNTER" => "Y",
//        "USE_FILTER" => "Y",
//        "FILTER_NAME" => "DISCOUNT_FILTER",
//        "FILTER_VIEW_MODE" => "VERTICAL",
//        "USE_COMPARE" => "N",
//        "PRICE_CODE" => BXConstants::PriceCode(),
//        "FILL_ITEM_ALL_PRICES" => "Y",
//        "USE_PRICE_COUNT" => "N",
//        "SHOW_PRICE_COUNT" => "100",
//        "PRICE_VAT_INCLUDE" => "Y",
//        "PRICE_VAT_SHOW_VALUE" => "N",
//        "PRODUCT_PROPERTIES" => "",
//        "USE_PRODUCT_QUANTITY" => "Y",
//        "CONVERT_CURRENCY" => "N",
//        "QUANTITY_FLOAT" => "N",
//        "OFFERS_CART_PROPERTIES" => array(
//            0 => "SIZES_SHOES",
//            1 => "SIZES_CLOTHES",
//            2 => "COLOR_REF",
//        ),
//        "SHOW_TOP_ELEMENTS" => "N",
//        "SECTION_COUNT_ELEMENTS" => "Y",
//        "SECTION_TOP_DEPTH" => "1",
//        "SECTIONS_VIEW_MODE" => "TILE",
//        "SECTIONS_SHOW_PARENT_NAME" => "N",
//        "PAGE_ELEMENT_COUNT" => "16",
//        "LINE_ELEMENT_COUNT" => "4",
//        "ELEMENT_SORT_FIELD" => 'name',
//        "ELEMENT_SORT_ORDER" => "asc",
//        "ELEMENT_SORT_FIELD2" => 'name',
//        "ELEMENT_SORT_ORDER2" => "desc",
//        "PROPERTY_CODE" => array(
//            0 => "NEWPRODUCT",
//            1 => "SALELEADER",
//            2 => "SPECIALOFFER",
//            3 => "",
//        ),
//        "INCLUDE_SUBSECTIONS" => "Y",
//        "LIST_META_KEYWORDS" => "-",
//        "LIST_META_DESCRIPTION" => "-",
//        "LIST_BROWSER_TITLE" => "-",
//        "OFFERS_FIELD_CODE" => array(
//            0 => "NAME",
//            1 => "PREVIEW_PICTURE",
//            2 => "DETAIL_PICTURE",
//            3 => "",
//        ),
//        "OFFERS_PROPERTY_CODE" => array(
//            0 => "SIZES_SHOES",
//            1 => "SIZES_CLOTHES",
//            2 => "COLOR_REF",
//            3 => "MORE_PHOTO",
//            4 => "ARTNUMBER",
//            5 => "",
//        ),
//        "OFFERS_LIMIT" => "0",
//        "SECTION_BACKGROUND_IMAGE" => "-",
//        "DETAIL_PROPERTY_CODE" => array(
//            0 => "NEWPRODUCT",
//            1 => "MANUFACTURER",
//            2 => "MATERIAL",
//        ),
//        "DETAIL_META_KEYWORDS" => "-",
//        "DETAIL_META_DESCRIPTION" => "-",
//        "DETAIL_BROWSER_TITLE" => "-",
//        "DETAIL_OFFERS_FIELD_CODE" => array(
//            0 => "NAME",
//            1 => "",
//        ),
//        "DETAIL_OFFERS_PROPERTY_CODE" => array(
//            0 => "ARTNUMBER",
//            1 => "SIZES_SHOES",
//            2 => "SIZES_CLOTHES",
//            3 => "COLOR_REF",
//            4 => "MORE_PHOTO",
//            5 => "",
//        ),
//        "DETAIL_BACKGROUND_IMAGE" => "-",
//        "LINK_IBLOCK_TYPE" => "",
//        "LINK_IBLOCK_ID" => "",
//        "LINK_PROPERTY_SID" => "",
//        "LINK_ELEMENTS_URL" => "link.php?PARENT_ELEMENT_ID=#ELEMENT_ID#",
//        "USE_ALSO_BUY" => "Y",
//        "ALSO_BUY_ELEMENT_COUNT" => "4",
//        "ALSO_BUY_MIN_BUYES" => "1",
//        "OFFERS_SORT_FIELD" => "sort",
//        "OFFERS_SORT_ORDER" => "desc",
//        "OFFERS_SORT_FIELD2" => "id",
//        "OFFERS_SORT_ORDER2" => "desc",
//        "PAGER_TEMPLATE" => "round",
//        "DISPLAY_TOP_PAGER" => "N",
//        "DISPLAY_BOTTOM_PAGER" => "Y",
//        "PAGER_TITLE" => "Товары",
//        "PAGER_SHOW_ALWAYS" => "N",
//        "PAGER_DESC_NUMBERING" => "N",
//        "PAGER_DESC_NUMBERING_CACHE_TIME" => "36000000",
//        "PAGER_SHOW_ALL" => "N",
//        "ADD_PICT_PROP" => "MORE_PHOTO",
//        "LABEL_PROP" => array(
//            0 => PROPERTY_KEY_VKUS,
//        ),
//        "PRODUCT_DISPLAY_MODE" => "Y",
//        "OFFER_ADD_PICT_PROP" => "MORE_PHOTO",
//        "OFFER_TREE_PROPS" => array(
//            0 => "SIZES_SHOES",
//            1 => "SIZES_CLOTHES",
//            2 => "COLOR_REF",
//            3 => "",
//        ),
//        "SHOW_DISCOUNT_PERCENT" => "Y",
//        "SHOW_OLD_PRICE" => "Y",
//        "MESS_BTN_BUY" => "Купить",
//        "MESS_BTN_ADD_TO_BASKET" => "В корзину",
//        "MESS_BTN_COMPARE" => "Сравнение",
//        "MESS_BTN_DETAIL" => "Подробнее",
//        "MESS_NOT_AVAILABLE" => "Нет в наличии",
//        "DETAIL_USE_VOTE_RATING" => "Y",
//        "DETAIL_VOTE_DISPLAY_AS_RATING" => "rating",
//        "DETAIL_USE_COMMENTS" => "Y",
//        "DETAIL_BLOG_USE" => "Y",
//        "DETAIL_VK_USE" => "N",
//        "DETAIL_FB_USE" => "Y",
//        "AJAX_OPTION_ADDITIONAL" => "",
//        "USE_STORE" => "Y",
//        "BIG_DATA_RCM_TYPE" => "personal",
//        "FIELDS" => array(
//            0 => "SCHEDULE",
//            1 => "STORE",
//            2 => "",
//        ),
//        "USE_MIN_AMOUNT" => "N",
//        "STORE_PATH" => "/store/#store_id#",
//        "MAIN_TITLE" => "Наличие на складах",
//        "MIN_AMOUNT" => "10",
//        "DETAIL_BRAND_USE" => "Y",
//        "DETAIL_BRAND_PROP_CODE" => array(
//            0 => "",
//            1 => "BRAND_REF",
//            2 => "",
//        ),
//        "COMPATIBLE_MODE" => "N",
//        "SIDEBAR_SECTION_SHOW" => "Y",
//        "SIDEBAR_DETAIL_SHOW" => "Y",
//        "SIDEBAR_PATH" => "/catalog/sidebar.php",
//        "COMPONENT_TEMPLATE" => "oshisha_catalog.catalog",
//        "HIDE_NOT_AVAILABLE_OFFERS" => "N",
//        "LABEL_PROP_MOBILE" => array(),
//        "LABEL_PROP_POSITION" => "top-left",
//        "COMMON_SHOW_CLOSE_POPUP" => "N",
//        "PRODUCT_SUBSCRIPTION" => "Y",
//        "DISCOUNT_PERCENT_POSITION" => "bottom-right",
//        "SHOW_MAX_QUANTITY" => "Y",
//        "MESS_BTN_SUBSCRIBE" => "Подписаться",
//        "SIDEBAR_SECTION_POSITION" => "right",
//        "SIDEBAR_DETAIL_POSITION" => "right",
//        "USER_CONSENT" => "N",
//        "USER_CONSENT_ID" => "0",
//        "USER_CONSENT_IS_CHECKED" => "Y",
//        "USER_CONSENT_IS_LOADED" => "N",
//        "USE_MAIN_ELEMENT_SECTION" => "N",
//        "DETAIL_STRICT_SECTION_CHECK" => "N",
//        "SET_LAST_MODIFIED" => "N",
//        "ADD_SECTIONS_CHAIN" => "Y",
//        "USE_SALE_BESTSELLERS" => "Y",
//        "FILTER_HIDE_ON_MOBILE" => "N",
//        "INSTANT_RELOAD" => "N",
//        "ADD_PROPERTIES_TO_BASKET" => "Y",
//        "PARTIAL_PRODUCT_PROPERTIES" => "N",
//        "USE_COMMON_SETTINGS_BASKET_POPUP" => "N",
//        "COMMON_ADD_TO_BASKET_ACTION" => "ADD",
//        "TOP_ADD_TO_BASKET_ACTION" => "ADD",
//        "SECTION_ADD_TO_BASKET_ACTION" => "ADD",
//        "DETAIL_ADD_TO_BASKET_ACTION" => array(
//            0 => "ADD",
//        ),
//        "DETAIL_ADD_TO_BASKET_ACTION_PRIMARY" => array(
//            0 => "ADD",
//        ),
//        "SEARCH_PAGE_RESULT_COUNT" => "50",
//        "SEARCH_RESTART" => "Y",
//        "SEARCH_NO_WORD_LOGIC" => "Y",
//        "SEARCH_USE_LANGUAGE_GUESS" => "Y",
//        "SEARCH_CHECK_DATES" => "Y",
//        "SECTIONS_HIDE_SECTION_NAME" => "N",
//        "LIST_PROPERTY_CODE_MOBILE" => array(),
//        "LIST_PRODUCT_BLOCKS_ORDER" => "price,props,sku,quantityLimit,quantity,buttons",
//        "LIST_PRODUCT_ROW_VARIANTS" => "[{'VARIANT':'3','BIG_DATA':false},{'VARIANT':'3','BIG_DATA':false},{'VARIANT':'3','BIG_DATA':false},{'VARIANT':'3','BIG_DATA':false}]",
//        "LIST_ENLARGE_PRODUCT" => "PROP",
//        "LIST_SHOW_SLIDER" => "Y",
//        "LIST_SLIDER_INTERVAL" => "3000",
//        "LIST_SLIDER_PROGRESS" => "N",
//        "DETAIL_SET_CANONICAL_URL" => "N",
//        "DETAIL_CHECK_SECTION_ID_VARIABLE" => "N",
//        "SHOW_DEACTIVATED" => "N",
//        "DETAIL_MAIN_BLOCK_PROPERTY_CODE" => array(),
//        "DETAIL_BLOG_URL" => "catalog_comments",
//        "DETAIL_BLOG_EMAIL_NOTIFY" => "N",
//        "DETAIL_FB_APP_ID" => "",
//        "DETAIL_IMAGE_RESOLUTION" => "16by9",
//        "DETAIL_PRODUCT_INFO_BLOCK_ORDER" => "sku,props",
//        "DETAIL_PRODUCT_PAY_BLOCK_ORDER" => "rating,price,priceRanges,quantityLimit,quantity,buttons",
//        "DETAIL_SHOW_SLIDER" => "N",
//        "DETAIL_DETAIL_PICTURE_MODE" => array(
//            0 => "POPUP",
//            1 => "MAGNIFIER",
//        ),
//        "DETAIL_ADD_DETAIL_TO_SLIDER" => "N",
//        "DETAIL_DISPLAY_PREVIEW_TEXT_MODE" => "E",
//        "MESS_PRICE_RANGES_TITLE" => "Цены",
//        "MESS_DESCRIPTION_TAB" => "Описание",
//        "MESS_PROPERTIES_TAB" => "Характеристики",
//        "MESS_COMMENTS_TAB" => "Комментарии",
//        "DETAIL_SHOW_POPULAR" => "Y",
//        "DETAIL_SHOW_VIEWED" => "Y",
//        "USE_GIFTS_DETAIL" => "Y",
//        "USE_GIFTS_SECTION" => "Y",
//        "USE_GIFTS_MAIN_PR_SECTION_LIST" => "Y",
//        "GIFTS_DETAIL_PAGE_ELEMENT_COUNT" => "3",
//        "GIFTS_DETAIL_HIDE_BLOCK_TITLE" => "N",
//        "GIFTS_DETAIL_BLOCK_TITLE" => "Выберите один из подарков",
//        "GIFTS_DETAIL_TEXT_LABEL_GIFT" => "Подарок",
//        "GIFTS_SECTION_LIST_PAGE_ELEMENT_COUNT" => "3",
//        "GIFTS_SECTION_LIST_HIDE_BLOCK_TITLE" => "N",
//        "GIFTS_SECTION_LIST_BLOCK_TITLE" => "Подарки к товарам этого раздела",
//        "GIFTS_SECTION_LIST_TEXT_LABEL_GIFT" => "Подарок",
//        "GIFTS_SHOW_DISCOUNT_PERCENT" => "Y",
//        "GIFTS_SHOW_OLD_PRICE" => "Y",
//        "GIFTS_SHOW_NAME" => "Y",
//        "GIFTS_SHOW_IMAGE" => "Y",
//        "GIFTS_MESS_BTN_BUY" => "Выбрать",
//        "GIFTS_MAIN_PRODUCT_DETAIL_PAGE_ELEMENT_COUNT" => "3",
//        "GIFTS_MAIN_PRODUCT_DETAIL_HIDE_BLOCK_TITLE" => "N",
//        "GIFTS_MAIN_PRODUCT_DETAIL_BLOCK_TITLE" => "Выберите один из товаров, чтобы получить подарок",
//        "STORES" => array(
//            0 => "",
//            1 => "",
//        ),
//        "USER_FIELDS" => array(
//            0 => "",
//            1 => "",
//        ),
//        "SHOW_EMPTY_STORE" => "Y",
//        "SHOW_GENERAL_STORE_INFORMATION" => "N",
//        "USE_BIG_DATA" => "N",
//        "USE_ENHANCED_ECOMMERCE" => "N",
//        "PAGER_BASE_LINK_ENABLE" => "N",
//        "LAZY_LOAD" => "Y",
//        "LOAD_ON_SCROLL" => "N",
//        "SHOW_404" => "N",
//        "MESSAGE_404" => "",
//        "DISABLE_INIT_JS_IN_COMPONENT" => "N",
//        "DETAIL_SET_VIEWED_IN_COMPONENT" => "N",
//        "LIST_ENLARGE_PROP" => "-",
//        "MESS_BTN_LAZY_LOAD" => "Показать ещё",
//        "SEF_URL_TEMPLATES" => array(
//            "sections" => "",
//            "section" => "#SECTION_CODE#/",
//            "element" => "#SECTION_CODE#/#ELEMENT_CODE#/",
//            "compare" => "compare/",
//            "smart_filter" => "#SECTION_CODE#/filter/#SMART_FILTER_PATH#/apply/",
//        )
//    );

    $arTest = array(
        'IBLOCK_TYPE' => '1c_catalog',
        'IBLOCK_ID' => IBLOCK_CATALOG,
        'FILL_ITEM_ALL_PRICES' => 'Y',
        'ELEMENT_SORT_FIELD2' => 'SERVICE_FIELD_POPULARITY',
        'ELEMENT_SORT_ORDER2' => 'DESC',
        'ELEMENT_SORT_FIELD' => 'SORT',
        'ELEMENT_SORT_ORDER' => 'ASC',
        'PROPERTY_CODE' =>
            array(
                0 => '',
                1 => 'NEWPRODUCT',
                2 => 'SALELEADER',
                3 => 'SPECIALOFFER',
                4 => '',
            ),
        'PROPERTY_CODE_MOBILE' => '',
        'META_KEYWORDS' => '-',
        'META_DESCRIPTION' => '-',
        'BROWSER_TITLE' => '-',
        'SET_LAST_MODIFIED' => 'N',
        'INCLUDE_SUBSECTIONS' => 'Y',
        'BASKET_URL' => '/personal/cart/',
        'ACTION_VARIABLE' => 'action',
        'PRODUCT_ID_VARIABLE' => 'id',
        'SECTION_ID_VARIABLE' => 'SECTION_ID',
        'PRODUCT_QUANTITY_VARIABLE' => 'quantity',
        'PRODUCT_PROPS_VARIABLE' => 'prop',
        'FILTER_NAME' => 'DISCOUNT_FILTER',
        'CACHE_TYPE' => 'N',
        'CACHE_TIME' => '',
        'CACHE_FILTER' => 'Y',
        'CACHE_GROUPS' => 'Y',
        'SET_TITLE' => 'Y',
        'MESSAGE_404' => '',
        'SET_STATUS_404' => 'Y',
        'SHOW_404' => 'Y',
        'FILE_404' => '',
        'DISPLAY_COMPARE' => 'N',
        'PAGE_ELEMENT_COUNT' => '36',
        'LINE_ELEMENT_COUNT' => '3',
        'PRICE_CODE' =>
            array(
                3 => 'Сайт скидка',
                2 => 'Основная',
                9 => 'b2b',
                4 => 'Розничная',
            ),
        'USE_PRICE_COUNT' => 'N',
        'SHOW_PRICE_COUNT' => '100',
        'PRICE_VAT_INCLUDE' => 'Y',
        'USE_PRODUCT_QUANTITY' => 'Y',
        'ADD_PROPERTIES_TO_BASKET' => 'Y',
        'PARTIAL_PRODUCT_PROPERTIES' => 'N',
        'PRODUCT_PROPERTIES' =>
            array(),
        'DISPLAY_TOP_PAGER' => 'N',
        'DISPLAY_BOTTOM_PAGER' => 'Y',
        'PAGER_TITLE' => 'Товары',
        'PAGER_SHOW_ALWAYS' => 'N',
        'PAGER_TEMPLATE' => 'round',
        'PAGER_DESC_NUMBERING' => 'N',
        'PAGER_DESC_NUMBERING_CACHE_TIME' => '36000000',
        'PAGER_SHOW_ALL' => 'N',
        'PAGER_BASE_LINK_ENABLE' => 'N',
        'PAGER_BASE_LINK' => NULL,
        'PAGER_PARAMS_NAME' => NULL,
        'LAZY_LOAD' => 'Y',
        'MESS_BTN_LAZY_LOAD' => 'Показать ещё',
        'LOAD_ON_SCROLL' => 'N',
        'OFFERS_CART_PROPERTIES' =>
            array(),
        'OFFERS_FIELD_CODE' =>
            array(
                0 => 'NAME',
                1 => 'PREVIEW_PICTURE',
                2 => 'DETAIL_PICTURE',
                3 => 'GRAMMOVKA_G',
                4 => 'SHTUK_V_UPAKOVKE',
                5 => 'TSVET',
            ),
        'OFFERS_PROPERTY_CODE' =>
            array(
                0 => 'MORE_PHOTO',
                1 => 'SIZES_SHOES',
                6 => 'SHTUK_V_UPAKOVKE',
                7 => 'TSVET',
                2 => 'GRAMMOVKA_G',
                3 => 'COLOR_REF',
                4 => 'ARTNUMBER',
                5 => '',
            ),
        'OFFERS_SORT_FIELD' => 'sort',
        'OFFERS_SORT_ORDER' => 'desc',
        'OFFERS_SORT_FIELD2' => 'id',
        'OFFERS_SORT_ORDER2' => 'desc',
        'OFFERS_LIMIT' => '5',
        'SECTION_URL' => '/catalog/#SECTION_CODE#/',
        'DETAIL_URL' => '/catalog/product/#ELEMENT_CODE#/',
        'USE_MAIN_ELEMENT_SECTION' => 'N',
        'CONVERT_CURRENCY' => 'N',
        'CURRENCY_ID' => NULL,
        'HIDE_NOT_AVAILABLE' => 'L',
        'HIDE_NOT_AVAILABLE_OFFERS' => 'N',
        'LABEL_PROP' =>
            array(
                0 => 'VKUS',
            ),
        'LABEL_PROP_MOBILE' => '',
        'LABEL_PROP_POSITION' => 'top-left',
        'ADD_PICT_PROP' => 'MORE_PHOTO',
        'PRODUCT_DISPLAY_MODE' => 'Y',
        'PRODUCT_BLOCKS_ORDER' => 'price,props,sku,quantityLimit,quantity,buttons',
        'PRODUCT_ROW_VARIANTS' => '[{\'VARIANT\':\'3\',\'BIG_DATA\':false},{\'VARIANT\':\'3\',\'BIG_DATA\':false},{\'VARIANT\':\'3\',\'BIG_DATA\':false},{\'VARIANT\':\'3\',\'BIG_DATA\':false}]',
        'ENLARGE_PRODUCT' => 'PROP',
        'ENLARGE_PROP' => '-',
        'SHOW_SLIDER' => 'Y',
        'SLIDER_INTERVAL' => '3000',
        'SLIDER_PROGRESS' => 'N',
        'OFFER_ADD_PICT_PROP' => 'MORE_PHOTO',
        'OFFER_TREE_PROPS' =>
            array(),
        'PRODUCT_SUBSCRIPTION' => 'Y',
        'SHOW_DISCOUNT_PERCENT' => 'Y',
        'DISCOUNT_PERCENT_POSITION' => 'bottom-right',
        'SHOW_OLD_PRICE' => 'Y',
        'SHOW_MAX_QUANTITY' => 'Y',
        'MESS_SHOW_MAX_QUANTITY' => 'Наличие',
        'RELATIVE_QUANTITY_FACTOR' => '',
        'MESS_RELATIVE_QUANTITY_MANY' => '',
        'MESS_RELATIVE_QUANTITY_FEW' => '',
        'MESS_BTN_BUY' => 'Купить',
        'MESS_BTN_ADD_TO_BASKET' => 'Забронировать',
        'MESS_BTN_SUBSCRIBE' => 'Подписаться',
        'MESS_BTN_DETAIL' => 'Подробнее',
        'MESS_NOT_AVAILABLE' => 'Нет в наличии',
        'MESS_BTN_COMPARE' => 'Сравнение',
        'USE_ENHANCED_ECOMMERCE' => 'N',
        'DATA_LAYER_NAME' => '',
        'BRAND_PROPERTY' => '',
        'TEMPLATE_THEME' => 'site',
        'ADD_SECTIONS_CHAIN' => 'Y',
        'ADD_TO_BASKET_ACTION' => 'ADD',
        'SHOW_CLOSE_POPUP' => 'N',
        'COMPARE_PATH' => '/catalog/compare/',
        'COMPARE_NAME' => NULL,
        'USE_COMPARE_LIST' => 'Y',
        'BACKGROUND_IMAGE' => '-',
        'COMPATIBLE_MODE' => 'N',
        'DISABLE_INIT_JS_IN_COMPONENT' => 'N',
    );

    $e = 'e';

    $APPLICATION->IncludeComponent(
        "bitrix:catalog.section",
        "oshisha_catalog.section",
        $arTest,
        false
    );
    ?>

</div>