<?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetPageProperty("title","Акции и скидки");
?>

<?$APPLICATION->IncludeComponent(
	"bitrix:news", 
	"promotions", 
	array(
		"DISPLAY_DATE" => "",
		"DISPLAY_PICTURE" => "",
		"DISPLAY_PREVIEW_TEXT" => "",
		"SEF_MODE" => "Y",
		"AJAX_MODE" => "N",
		"IBLOCK_TYPE" => "content",
		"IBLOCK_ID" => "28",
		"NEWS_COUNT" => "1000",
		"USE_SEARCH" => "N",
		"USE_RSS" => "N",
		"USE_RATING" => "N",
		"USE_CATEGORIES" => "N",
		"USE_REVIEW" => "",
		"USE_FILTER" => "Y",
		"SORT_BY1" => "SORT",
		"SORT_ORDER1" => "ASC",
		"SORT_BY2" => "ACTIVE_TO",
		"SORT_ORDER2" => "nulls,DESC",
		"CHECK_DATES" => "N",
		"PREVIEW_TRUNCATE_LEN" => "",
		"LIST_ACTIVE_DATE_FORMAT" => "j F Y",
		"LIST_FIELD_CODE" => array(
			0 => "ACTIVE_TO",
			1 => "",
		),
		"LIST_PROPERTY_CODE" => array(
			0 => "MARKER",
			1 => "SHOW_TIMER",
			2 => "",
		),
		"HIDE_LINK_WHEN_NO_DETAIL" => "N",
		"DISPLAY_NAME" => "N",
		"META_KEYWORDS" => "META_KEYWORDS",
		"META_DESCRIPTION" => "META_DESCRIPTION",
		"BROWSER_TITLE" => "BROWSER_TITLE",
		"DETAIL_SET_CANONICAL_URL" => "N",
		"DETAIL_ACTIVE_DATE_FORMAT" => "j F Y",
		"DETAIL_FIELD_CODE" => array(
			0 => "ACTIVE_TO",
			1 => "",
		),
		"DETAIL_PROPERTY_CODE" => array(
			0 => "MARKER",
			1 => "SHOW_TIMER",
			2 => "SALE_DICOUNT_ID",
			3 => "BRANDS",
			4 => "PRODUCTS",
			5 => "OBJECT",
			6 => "SECTIONS",
			7 => "",
		),
		"DETAIL_DISPLAY_TOP_PAGER" => "N",
		"DETAIL_DISPLAY_BOTTOM_PAGER" => "N",
		"DETAIL_PAGER_TITLE" => "",
		"DETAIL_PAGER_TEMPLATE" => "",
		"DETAIL_PAGER_SHOW_ALL" => "N",
		"SET_TITLE" => "Y",
		"ADD_SECTIONS_CHAIN" => "Y",
		"ADD_ELEMENT_CHAIN" => "Y",
		"SET_LAST_MODIFIED" => "N",
		"PAGER_BASE_LINK_ENABLE" => "N",
		"SET_STATUS_404" => "Y",
		"SHOW_404" => "N",
		"MESSAGE_404" => "",
		"PAGER_BASE_LINK" => "",
		"PAGER_PARAMS_NAME" => "",
		"INCLUDE_IBLOCK_INTO_CHAIN" => "N",
		"USE_PERMISSIONS" => "N",
		"GROUP_PERMISSIONS" => "",
		"CACHE_TYPE" => "A",
		"CACHE_TIME" => "86400",
		"CACHE_FILTER" => "Y",
		"CACHE_GROUPS" => "Y",
		"DISPLAY_TOP_PAGER" => "N",
		"DISPLAY_BOTTOM_PAGER" => "Y",
		"PAGER_TITLE" => "Акции и скидки",
		"PAGER_SHOW_ALWAYS" => "N",
		"PAGER_TEMPLATE" => "arrows",
		"PAGER_DESC_NUMBERING" => "N",
		"PAGER_DESC_NUMBERING_CACHE_TIME" => "",
		"PAGER_SHOW_ALL" => "N",
		"FILTER_NAME" => "arPromoFilter",
		"FILTER_FIELD_CODE" => array(
			0 => "",
			1 => "",
		),
		"FILTER_PROPERTY_CODE" => array(
			0 => "",
			1 => "",
		),
		"NUM_NEWS" => "",
		"NUM_DAYS" => "",
		"YANDEX" => "",
		"MAX_VOTE" => "",
		"VOTE_NAMES" => "",
		"CATEGORY_IBLOCK" => "",
		"CATEGORY_CODE" => "",
		"CATEGORY_ITEMS_COUNT" => "",
		"MESSAGES_PER_PAGE" => "",
		"USE_CAPTCHA" => "",
		"REVIEW_AJAX_POST" => "",
		"PATH_TO_SMILE" => "",
		"FORUM_ID" => "",
		"URL_TEMPLATES_READ" => "",
		"SHOW_LINK_TO_FORUM" => "",
		"POST_FIRST_MESSAGE" => "",
		"SEF_FOLDER" => "/promotions/",
		"AJAX_OPTION_JUMP" => "N",
		"AJAX_OPTION_STYLE" => "N",
		"AJAX_OPTION_HISTORY" => "N",
		"USE_SHARE" => "",
		"SHARE_HIDE" => "",
		"SHARE_TEMPLATE" => "",
		"SHARE_HANDLERS" => "",
		"SHARE_SHORTEN_URL_LOGIN" => "",
		"SHARE_SHORTEN_URL_KEY" => "",
		"COMPONENT_TEMPLATE" => "promotions",
		"AJAX_OPTION_ADDITIONAL" => "",
		"INCLUDE_SUBSECTIONS" => "N",
		"CATALOG_IBLOCK_TYPE" => "catalog",
		"CATALOG_IBLOCK_ID" => "24",
		"CATALOG_INCLUDE_SUBSECTIONS" => "Y",
		"CATALOG_HIDE_NOT_AVAILABLE" => "Y",
		"CATALOG_HIDE_NOT_AVAILABLE_OFFERS" => "N",
		"CATALOG_ELEMENT_SORT_FIELD" => "PROPERTY_USE_AVAILABLE",
		"CATALOG_ELEMENT_SORT_ORDER" => "asc",
		"CATALOG_ELEMENT_SORT_FIELD2" => "sort",
		"CATALOG_ELEMENT_SORT_ORDER2" => "asc",
		"CATALOG_OFFERS_SORT_FIELD" => "sort",
		"CATALOG_OFFERS_SORT_ORDER" => "asc",
		"CATALOG_OFFERS_SORT_FIELD2" => "id",
		"CATALOG_OFFERS_SORT_ORDER2" => "desc",
		"CATALOG_OFFERS_PROPERTY_CODE" => array(
			0 => "SIZE",
			1 => "TSVET_POSTAVSHCHIKA",
			2 => "RAZMER_ROSSIYSKIY_OBUV",
			3 => "RAZMER_POSTAVSHCHIKA_ODEZHDA",
			4 => "RAZMER_RAMY",
			6 => "",
		),
		"CATALOG_PRODUCT_DISPLAY_MODE" => "Y",
		"CATALOG_OFFER_TREE_PROPS" => array(
			1 => "TSVET_POSTAVSHCHIKA",
			2 => "RAZMER_ROSSIYSKIY_OBUV",
			3 => "RAZMER_POSTAVSHCHIKA_ODEZHDA",
			4 => "RAZMER_RAMY",
		),
		"CATALOG_PRODUCT_SUBSCRIPTION" => "Y",
		"CATALOG_SHOW_DISCOUNT_PERCENT" => "Y",
		"CATALOG_SHOW_OLD_PRICE" => "Y",
		"CATALOG_SHOW_MAX_QUANTITY" => "M",
		"CATALOG_MESS_SHOW_MAX_QUANTITY" => "В наличии",
		"CATALOG_RELATIVE_QUANTITY_FACTOR" => "5",
		"CATALOG_MESS_RELATIVE_QUANTITY_MANY" => "много",
		"CATALOG_MESS_RELATIVE_QUANTITY_FEW" => "мало",
		"CATALOG_MESS_BTN_BUY" => "Купить",
		"CATALOG_MESS_BTN_ADD_TO_BASKET" => "Купить",
		"CATALOG_MESS_BTN_SUBSCRIBE" => "Сообщить о поступлении",
		"CATALOG_MESS_BTN_DETAIL" => "Подробнее",
		"CATALOG_MESS_NOT_AVAILABLE" => "Нет в наличии",
		"CATALOG_USE_MAIN_ELEMENT_SECTION" => "N",
		"CATALOG_PRICE_CODE" => BxConstants::PriceCode(),
		"CATALOG_USE_PRICE_COUNT" => "Y",
		"CATALOG_SHOW_PRICE_COUNT" => "1",
		"CATALOG_PRICE_VAT_INCLUDE" => "Y",
		"CATALOG_CONVERT_CURRENCY" => "N",
		"CATALOG_CURRENCY_ID" => "",
		"CATALOG_BASKET_URL" => "/personal/cart/",
		"CATALOG_USE_PRODUCT_QUANTITY" => "Y",
		"CATALOG_ADD_PROPERTIES_TO_BASKET" => "Y",
		"CATALOG_PARTIAL_PRODUCT_PROPERTIES" => "Y",
		"CATALOG_PRODUCT_PROPERTIES" => array(
		),
		"CATALOG_OFFERS_CART_PROPERTIES" => array(
			0 => "SIZE",
		),
		"CATALOG_ADD_TO_BASKET_ACTION" => "ADD",
		"CATALOG_USE_REVIEW" => "Y",
		"CATALOG_REVIEWS_IBLOCK_TYPE" => "reviews",
		"CATALOG_REVIEWS_IBLOCK_ID" => "31",
		"CATALOG_DISPLAY_COMPARE" => "Y",
		"CATALOG_COMPARE_PATH" => "/catalog/compare/",
		"CATALOG_MESS_BTN_COMPARE" => "Добавить к сравнению",
		"CATALOG_COMPARE_NAME" => "CATALOG_COMPARE_LIST",
		"SHOW_OBJECT" => "Y",
		"OBJECTS_IBLOCK_TYPE" => "content",
		"OBJECTS_IBLOCK_ID" => "13",
		"OBJECTS_PROPERTY_CODE" => array(
			0 => "ADDRESS",
			1 => "MAP",
			2 => "MON",
			3 => "TUE",
			4 => "WED",
			5 => "THU",
			6 => "FRI",
			7 => "SAT",
			8 => "SUN",
			9 => "TOUR_3D",
			10 => "AFFILIATES",
			11 => "PHONE",
			12 => "EMAIL",
			13 => "SKYPE",
			14 => "PHONE_SMS",
			15 => "EMAIL_EMAIL",
			16 => "",
		),
		"OBJECTS_SHOW_PROMOTIONS" => "Y",
		"OBJECTS_USE_REVIEW" => "Y",
		"OBJECTS_REVIEWS_IBLOCK_TYPE" => "reviews",
		"OBJECTS_REVIEWS_IBLOCK_ID" => "21",
		"STRICT_SECTION_CHECK" => "N",
		"SEF_URL_TEMPLATES" => array(
			"news" => "",
			"section" => "",
			"detail" => "#ELEMENT_ID#/",
		)
	),
	false
);?>

<?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>